@baseUrl = http://localhost:8080

#### hello world
GET {{baseUrl}}/

### Get all Software Engineers
GET {{baseUrl}}/api/v1/software-engineers

### Get Software Engineer by ID
GET {{baseUrl}}/api/v1/software-engineers/2

### post engineer
POST {{baseUrl}}/api/v1/software-engineers/add
Content-Type: application/json

{
    "name": "Emp 3",
    "techStack": "java, react"
}